bubbles/reporting/urls.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
from django.urls import path
from . import views, api

app_name = "reporting"
urlpatterns = [
    path("", views.index, name="index"),
    path("equipment/size", views.equipment_size, name="size"),
    path("equipment/repair", views.equipment_under_repair, name="repair"),
    path("api/equipment/size/<str:item_type>", api.equipment_size, name="api-size"),
]

bubbles/urls.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
"""bubbles URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import include, path

from .admin import admin_site

urlpatterns = [
    path("", include("bubbles.rentals.urls")),
    path("", include("django_prometheus.urls")),
    path("inventory/", include("bubbles.inventory.urls")),
    path("admin/", admin_site.urls),
    path("admin/reporting/", include("bubbles.reporting.urls")),
    path("accounts/", include("bubbles.registration.urls")),
    path("docs/", include("bubbles.pages.urls")),
    path("temp/", include("django.contrib.admindocs.urls")),
]

bubbles/reporting/models.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
from django.db import models

# Create your models here.

bubbles/reporting/views.py
###########################################################################
# Bubbles is Copyright (C) 2018 Kyle Robbertze <krobbertze@gmail.com>
#
# Bubbles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Bubbles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bubbles. If not, see <http://www.gnu.org/licenses/>.
###########################################################################
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.db.models import Q

from bubbles.inventory import get_item_size_map, get_size_breakdown, get_items_in_state
from bubbles.inventory.models import Item


def index(request):
    context = {
        "title": _("Reporting"),
    }
    return render(request, "reporting/index.html", context)


def equipment_size(request):
    state_filter = ~Q(state=Item.CONDEMNED)
    item_types = get_item_size_map(state_filter).keys()
    size_count = get_size_breakdown("BCD", state_filter)
    context = {
        "title": _("Size Breakdown"),
        "item_types": item_types,
        "item": "BCD",
        "result": size_count,
    }
    return render(request, "reporting/equipment_size.html", context)


def equipment_under_repair(request):
    result = get_items_in_state(Item.REPAIR)
    context = {
        "title": _("Equipment Under Repair"),
        "result": result,
    }
    return render(request, "reporting/equipment_size.html", context)

bubbles/reporting/templates/reporting/equipment_size.html
{% extends "bubbles/base.html" %}
{% load static %}

{% block extra_head %}
<script src="{% static 'vendor/d3/d3.min.js' %}"></script>
<script src="{% static 'js/display_graph.js' %}"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-10">
    {% if item %}
    <h2 id="item-heading">{{ item }}</h2>
    {% endif %}
  </div>
  <div class="col-sm-2">
    {% if item_types %}
    <select id="item-type" onchange="updateGraph()">
      {% for type in item_types %}
      <option value="{{ type }}">{{ type }}</option>
      {% endfor %}
    </select>
    {% endif %}
  </div>
</div>
<div id="chart-view" class="col-sm-12">
<svg class="chart"></svg>
</div>
<div class="results">
  {% for k,v in result.items %}
  <div class="result" id="{{ k }}" value="{{ v }}"></div>
  {% endfor %}
</div>
{% endblock %}

bubbles/reporting/templates/reporting/index.html
{% extends "bubbles/base.html" %}

{% block content %}
<div class="row">
  <div class="col-sm-6">
    <h2>Equipment</h2>
    <ul class="list-group">
      <li class="list-group-item">
        <a href="{% url 'reporting:size' %}">Breakdown by size</a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'reporting:repair' %}">Under repair</a>
      </li>
    </ul>
  </div>
  <div class="col-sm-6">
    <h2>Rentals</h2>
    <ul class="list-group">
      <li class="list-group-item">
        <a href="#">By period</a>
      </li>
    </ul>
  </div>
</div>
{% endblock %}